source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'pry'
gem 'rspec'
gem 'json'
gem 'date'
gem 'dotenv'
gem 'mail'
gem 'poltergeist'
gem 'pry-byebug'
gem 'rake'
gem 'report_builder'
gem 'rubocop', '0.59.2', require: false
gem 'selenium-webdriver'
gem 'show_me_the_cookies'
gem 'simple_xlsx_reader'
gem 'site_prism', '~> 4.0', '>= 4.0.3'
gem 'site_prism-table'
gem 'spreadsheet'
gem 'syntax'
gem 'time_diff', '~> 0.3.0'
gem 'touch_action'
gem 'webdrivers', '~> 3.0'